# Generated by Django 5.0.14 on 2025-08-02 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autore',
            fields=[
                ('codice', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=60)),
                ('cognome', models.CharField(max_length=60)),
                ('nazione', models.CharField(max_length=40)),
                ('data_nascita', models.DateField()),
                ('tipo', models.CharField(choices=[('vivo', 'Vivo'), ('morto', 'Morto')], max_length=5)),
                ('data_morte', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Opera',
            fields=[
                ('codice', models.AutoField(primary_key=True, serialize=False)),
                ('titolo', models.CharField(max_length=120)),
                ('anno_acquisto', models.PositiveSmallIntegerField()),
                ('anno_realizzazione', models.PositiveSmallIntegerField()),
                ('tipo', models.CharField(choices=[('Quadro', 'Quadro'), ('Scultura', 'Scultura')], max_length=8)),
                ('immagine', models.ImageField(blank=True, null=True, upload_to='opere/')),
            ],
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('numero', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=60)),
                ('superficie', models.PositiveIntegerField(help_text='metri quadri')),
            ],
        ),
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('codice', models.AutoField(primary_key=True, serialize=False)),
                ('descrizione', models.TextField()),
            ],
        ),
        migrations.AddConstraint(
            model_name='autore',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('data_morte__isnull', True), ('tipo', 'vivo')), models.Q(('data_morte__isnull', False), ('tipo', 'morto')), _connector='OR'), name='autore_vivo_morto_constraint'),
        ),
        migrations.AddField(
            model_name='opera',
            name='autore',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opere', to='gallery.autore'),
        ),
        migrations.AddField(
            model_name='opera',
            name='esposta_in_sala',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gallery.sala'),
        ),
        migrations.AddField(
            model_name='sala',
            name='tema',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gallery.tema'),
        ),
    ]
